#! /usr/bin/python
import argparse
from Converters import GCode

def main():
	parser = argparse.ArgumentParser(description='Python CLI tool to convert to CNC-CON serial format')
	parser.add_argument('files', metavar='FILE', nargs='+', help='files to convert')
	args = parser.parse_args()

	for file in args.files:
		parser = GCode.GCodeParser()
		parser.readFile(file)
		parser.removeTapeMarkers()
		parser.removeInlineComments()
		parser.removeBlockSkipLines()
		parser.normalizeAddressWhitespace()
		parser.readSequenceNumbers()

		inter = GCode.GCodeInterpreter()
		inter.run(parser)

if __name__ == "__main__":
	main()
