#! /usr/bin/python
import sys
import os
import pty
import select

from Control.MockMachine import MockMachine

def main():
	master, slave = pty.openpty()

	print "Slave Terminal: %s" % (os.ttyname(slave))
	#os.close(slave)

	machine = MockMachine()

	buffer = ""
	while True:
		buffer += os.read(master, 128).replace('\r\n', '\n').replace('\r', '\n')

		pos = buffer.find('\n')
		if(pos < 0): continue
		cmd = buffer[:pos]
		buffer = buffer[pos + 1:]

		print "<<< %s" % cmd
		reply = machine.process(cmd)

		if reply != "":
			print ">>> %s" % reply
			os.write(master, reply + '\r')

if __name__ == "__main__":
	main()
