#! /usr/bin/python
from Control import ControlMainWindow
from PySide import QtGui
import sys

if __name__ == "__main__":
	app = QtGui.QApplication(sys.argv)
	mainwin = ControlMainWindow.ControlMainWindow()
	mainwin.show()
	sys.exit(app.exec_())

